# Generated by Django 3.1.7 on 2021-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='default.jpg', upload_to='productImg'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.CharField(max_length=150),
        ),
    ]
