# Generated by Django 3.1.7 on 2021-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210415_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.CharField(max_length=100),
        ),
    ]
