# Generated by Django 3.1.7 on 2021-04-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210415_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='date_poted',
            new_name='date_posted',
        ),
    ]
