# Generated by Django 3.1.7 on 2021-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
